### PR TITLE
Improvement: Refactor unionwriter ahead of adding VisitWithContext and AcceptWithContext methods.

### PR DESCRIPTION
**Pull request by jamesross3**
This change is [Reviewable](https://reviewable.io/reviews/palantir/conjure-go/143)

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/conjure-go](https://github.com/palantir/conjure-go), @jamesross3! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by jamesross3** [comment]
@bmoylan

**Review by bmoylan — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/palantir/conjure-go/143)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by jamesross3** [comment]
==MERGE_WHEN_READY==

**Pull request merged**
