### PR TITLE
Fix: add support for all collection query param types

### LINKED ISSUE #62: Lists and Sets as query parameters breaks server code generation
## What happened?

Server code generation breaks with the following error if you use a `list` or `set` argument for a `query` `param-type`:

```
Error: failed to generate Conjure: failed to generate AST for service FooService: can not assign string expression to list type
```

To reproduce, use this conjure yaml:

```yaml
types:
  definitions:
    objects:
services:
  FooService:
    name: "Foo Service"
    package: com.palantir.foo
    base-path: /foo
    endpoints:
      bar:
        http: GET /bar
        args:
          listOfStrings:
            param-type: query
            type: list<string> # this breaks
```

Which produces the following conjure IR:

```json
{
  "version" : 1,
  "errors" : [ ],
  "types" : [ ],
  "services" : [ {
    "serviceName" : {
      "name" : "FooService",
      "package" : "com.palantir.foo"
    },
    "endpoints" : [ {
      "endpointName" : "bar",
      "httpMethod" : "GET",
      "httpPath" : "/foo/bar",
      "args" : [ {
        "argName" : "listOfStrings",
        "type" : {
          "type" : "list",
          "list" : {
            "itemType" : {
              "type" : "primitive",
              "primitive" : "STRING"
            }
          }
        },
        "paramType" : {
          "type" : "query",
          "query" : {
            "paramId" : "listOfStrings"
          }
        },
        "markers" : [ ]
      } ],
      "markers" : [ ]
    } ]
  } ]
}
```

Now reproduce the failure by running `conjure-go` directly with and without server code generation:

```
# works fine without generating the server code
$ go run main.go --output /tmp/ /tmp/conjure.json

# breaks if you generate the server code
$ go run main.go --output /tmp/ --server /tmp/conjure.json
Error: failed to generate Conjure: failed to generate AST for service FooService: can not assign string expression to list type
exit status 1
```

## What did you want to happen?

Server code generation should work in this case.

### PR DESCRIPTION
**Pull request by nmiyake**
## Before this PR
Query parameter collections only supports string as the primitive type in the collection (the original server generator did not support any collections as query parameters, but special-case support for string collections was added in #105)

## After this PR
==COMMIT_MSG==
Supports generating server code for a definition that has a query parameter that is a collection of a primitive.

Fixes #62
==COMMIT_MSG==

## Possible downsides?
None specifically. I'm not confident that this change alone adds full support for all query parameter rules supported by the Conjure definition (I haven't tested cases like having the query parameter be an alias that resolves to a primitive, which is supported by the spec), but at the very least it removes the string-only special-casing for collections, and generally brings the Go server generator closer to completion.

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/conjure-go/108)

### CODE REVIEW

**Review by k-simons — COMMENTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/palantir/conjure-go/108)* status: all files reviewed, 5 unresolved discussions (waiting on @nmiyake)

___
*[conjure/visitors/visit_string_param.go, line 32 at r1](https://reviewable.io/reviews/palantir/conjure-go/108#-M-fiSvRBkYcmpQHooii:-M-fiSvRBkYcmpQHooij:b-ov9pzw) ([raw file](https://github.com/palantir/conjure-go/blob/f3b15468bb6a58c6011860ff98c76ffa77e08cd4/conjure/visitors/visit_string_param.go#L32)):*
> ```Go
> )
> 
> func ParseStringParam(argName spec.ArgumentName, argType spec.Type, stringExpr astgen.ASTExpr, info types.PkgInfo) ([]astgen.ASTStmt, error) {
> ```

Should this function name and underyling struct be renamed?
___
*[conjure/visitors/visit_string_param.go, line 319 at r1](https://reviewable.io/reviews/palantir/conjure-go/108#-M-fibAiAaTVAoa8N5m4:-M-fibAiAaTVAoa8N5m5:b-2epozt) ([raw file](https://github.com/palantir/conjure-go/blob/f3b15468bb6a58c6011860ff98c76ffa77e08cd4/conjure/visitors/visit_string_param.go#L319)):*
> ```Go
> 	})
> 
> 	//ParseStringParam()
> ```

Remove these comments?
___
*[conjure/visitors/visit_string_param_test.go, line 228 at r1](https://reviewable.io/reviews/palantir/conjure-go/108#-M-fiqZm0cVV9tSScNVM:-M-fiqZm0cVV9tSScNVN:b98b1z4) ([raw file](https://github.com/palantir/conjure-go/blob/f3b15468bb6a58c6011860ff98c76ffa77e08cd4/conjure/visitors/visit_string_param_test.go#L228)):*
> ```Go
> 				"strconv",
> 			},
> 			ExpectedSrc: `var myArg []int
> ```

Should we add additional tests for other primitives? Or is the compilations of the generated code enough?
___
*[integration_test/testgenerated/server/server-service.yml, line 35 at r1](https://reviewable.io/reviews/palantir/conjure-go/108#-M-fiyny3HQpp50YXF3U:-M-fiyny3HQpp50YXF3V:b3kqovx) ([raw file](https://github.com/palantir/conjure-go/blob/f3b15468bb6a58c6011860ff98c76ffa77e08cd4/integration_test/testgenerated/server/server-service.yml#L35)):*
> ```YAML
>             type: list<string>
>             param-type: query
>       queryParamListBoolean:
> ```

Out of curiosity how did you go from `yml` changes to regenerate conjure code? I had to do it pretty manually when I was making changes
___
*[integration_test/testgenerated/server/api/servers.conjure.go, line 29 at r1](https://reviewable.io/reviews/palantir/conjure-go/108#-M-fjaOb-27tDXDWEqn7:-M-fjaOb-27tDXDWEqn8:bz8rl5g) ([raw file](https://github.com/palantir/conjure-go/blob/f3b15468bb6a58c6011860ff98c76ffa77e08cd4/integration_test/testgenerated/server/api/servers.conjure.go#L29)):*
> ```Go
> 	GetPathParamAlias(ctx context.Context, authHeader bearertoken.Token, myPathParamArg StringAlias) error
> 	QueryParamList(ctx context.Context, authHeader bearertoken.Token, myQueryParam1Arg []string) error
> 	QueryParamListBoolean(ctx context.Context, authHeader bearertoken.Token, myQueryParam1Arg []bool) error
> ```

At some point should be be used in the testing harness to client -> server code?

**Review by nmiyake — COMMENTED** [review]
Thanks for the review! Addressed PR feedback.

> *[Reviewable](https://reviewable.io/reviews/palantir/conjure-go/108#-:-M-qgO6s-0QAWeydLjxp:b-u7mom1)* status: 4 of 8 files reviewed, 5 unresolved discussions (waiting on @k-simons)

___
*[conjure/visitors/visit_string_param_test.go, line 228 at r1](https://reviewable.io/reviews/palantir/conjure-go/108#-M-fiqZm0cVV9tSScNVM:-M-qfXvl5LJU_yuQ-Ktp:b-elanjv) ([raw file](https://github.com/palantir/conjure-go/blob/f3b15468bb6a58c6011860ff98c76ffa77e08cd4/conjure/visitors/visit_string_param_test.go#L228)):*
<details><summary><i>Previously, k-simons wrote…</i></summary><blockquote>

Should we add additional tests for other primitives? Or is the compilations of the generated code enough?
</blockquote></details>

Done -- formalized this a bit more and added tests for all primitives and optionals/sets/lists of those primitives.
___
*[integration_test/testgenerated/server/server-service.yml, line 35 at r1](https://reviewable.io/reviews/palantir/conjure-go/108#-M-fiyny3HQpp50YXF3U:-M-qfi2931KFbtoGmt2A:by575jv) ([raw file](https://github.com/palantir/conjure-go/blob/f3b15468bb6a58c6011860ff98c76ffa77e08cd4/integration_test/testgenerated/server/server-service.yml#L35)):*
<details><summary><i>Previously, k-simons wrote…</i></summary><blockquote>

Out of curiosity how did you go from `yml` changes to regenerate conjure code? I had to do it pretty manually when I was making changes
</blockquote></details>

You can run `go generate` in `integration_test/testgenerated` to regenerate the output (or run `./godelw generate` in the project)
___
*[integration_test/testgenerated/server/api/servers.conjure.go, line 29 at r1](https://reviewable.io/reviews/palantir/conjure-go/108#-M-fjaOb-27tDXDWEqn7:-M-qfyQW-_TUlUW2xVMn:b8owkpq) ([raw file](https://github.com/palantir/conjure-go/blob/f3b15468bb6a58c6011860ff98c76ffa77e08cd4/integration_test/testgenerated/server/api/servers.conjure.go#L29)):*
<details><summary><i>Previously, k-simons wrote…</i></summary><blockquote>

At some point should be be used in the testing harness to client -> server code?
</blockquote></details>

Yeah ideally we would test all of them, but it's also a decent amount of effort to hand-write tests for all the endpoints -- not sure what the best trade-off is here.
___
*[conjure/visitors/visit_string_param.go, line 32 at r1](https://reviewable.io/reviews/palantir/conjure-go/108#-M-fiSvRBkYcmpQHooii:-M-qYjvn4Qe25q8ks0ux:b-896fix) ([raw file](https://github.com/palantir/conjure-go/blob/f3b15468bb6a58c6011860ff98c76ffa77e08cd4/conjure/visitors/visit_string_param.go#L32)):*
<details><summary><i>Previously, k-simons wrote…</i></summary><blockquote>

Should this function name and underyling struct be renamed?
</blockquote></details>

Done.
___
*[conjure/visitors/visit_string_param.go, line 319 at r1](https://reviewable.io/reviews/palantir/conjure-go/108#-M-fibAiAaTVAoa8N5m4:-M-qXF1hBQERF5hBELbt:b-896fix) ([raw file](https://github.com/palantir/conjure-go/blob/f3b15468bb6a58c6011860ff98c76ffa77e08cd4/conjure/visitors/visit_string_param.go#L319)):*
<details><summary><i>Previously, k-simons wrote…</i></summary><blockquote>

Remove these comments?
</blockquote></details>

Done.

**Review by k-simons — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/palantir/conjure-go/108)* status: 4 of 8 files reviewed, 3 unresolved discussions (waiting on @k-simons and @nmiyake)

___
*[integration_test/testgenerated/server/server-service.yml, line 35 at r1](https://reviewable.io/reviews/palantir/conjure-go/108#-M-fiyny3HQpp50YXF3U:-M-uuklg4u-86aJ9pVnF:b-16a6cm) ([raw file](https://github.com/palantir/conjure-go/blob/f3b15468bb6a58c6011860ff98c76ffa77e08cd4/integration_test/testgenerated/server/server-service.yml#L35)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

You can run `go generate` in `integration_test/testgenerated` to regenerate the output (or run `./godelw generate` in the project)
</blockquote></details>

awesome thats great to know!

**Comment by k-simons** [comment]
LGTM 👍

**Pull request merged**
