### PR TITLE
Add AcceptWithContext methods for union types.

### PR DESCRIPTION
**Pull request by jamesross3**
`AcceptWithContext` takes a context and a `<UnionTypeName>VisitorWithContext` as arguments, and passes the provided context when invoking `<UnionTypeName>VisitorWithContext`.

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/conjure-go/149)

### CODE REVIEW

**Comment by jamesross3** [comment]
@bmoylan

**Review by bmoylan — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/palantir/conjure-go/149)* status: all files reviewed, 1 unresolved discussion (waiting on @jamesross3)

___
*[integration_test/testgenerated/objects/api/unions.conjure.go, line 117 at r3](https://reviewable.io/reviews/palantir/conjure-go/149#-MIyZJOB4le8hl5UB3BS:-MIyZJOB4le8hl5UB3BT:b-qd6agm) ([raw file](https://github.com/palantir/conjure-go/blob/a8d2e58dcd2a4e7cacbdb5d0dc4d8ef525ffef47/integration_test/testgenerated/objects/api/unions.conjure.go#L117)):*
> ```Go
> }
> 
> func (u *ExampleUnion) AcceptWithContext(ctx context.Context, v ExampleUnionVisitorWithContext) error {
> ```

can you add something in objects_test.go that exercises this? like an implementation that only implements the WithContext visitor (even a mock if you want) and verify everything is called correctly

**Comment by bmoylan** [comment]
___
*[integration_test/testgenerated/objects/objects_test.go, line 311 at r4](https://reviewable.io/reviews/palantir/conjure-go/149#-MIydrrPCwFLGttSJX-N:-MIydrrPCwFLGttSJX-O:b-mog5s) ([raw file](https://github.com/palantir/conjure-go/blob/c8e75ca64c4cd17c7440f412bff9220cd455b2dc/integration_test/testgenerated/objects/objects_test.go#L311)):*
> ```Go
> 		t.Run(currCase.name, func(t *testing.T) {
> 			var v visitorWithContext
> 			ctx := context.WithValue(context.Background(), visitorCtxKeyName, "this value should be overwritten!")
> ```

should you add a second value to it to make sure that the same context is being used and the other key is preserved unchanged?

**Review by bmoylan — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/palantir/conjure-go/149)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by jamesross3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/palantir/conjure-go/149)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[integration_test/testgenerated/objects/objects_test.go, line 311 at r4](https://reviewable.io/reviews/palantir/conjure-go/149#-MIydrrPCwFLGttSJX-N:-MIyfqQOCawLb0ZP_eqO:bb6un1j) ([raw file](https://github.com/palantir/conjure-go/blob/c8e75ca64c4cd17c7440f412bff9220cd455b2dc/integration_test/testgenerated/objects/objects_test.go#L311)):*
<details><summary><i>Previously, bmoylan (Brad Moylan) wrote…</i></summary><blockquote>

should you add a second value to it to make sure that the same context is being used and the other key is preserved unchanged?
</blockquote></details>

Done
___
*[integration_test/testgenerated/objects/api/unions.conjure.go, line 117 at r3](https://reviewable.io/reviews/palantir/conjure-go/149#-MIyZJOB4le8hl5UB3BS:-MIyfr8n4HjGh26HqkP4:bb6un1j) ([raw file](https://github.com/palantir/conjure-go/blob/a8d2e58dcd2a4e7cacbdb5d0dc4d8ef525ffef47/integration_test/testgenerated/objects/api/unions.conjure.go#L117)):*
<details><summary><i>Previously, bmoylan (Brad Moylan) wrote…</i></summary><blockquote>

can you add something in objects_test.go that exercises this? like an implementation that only implements the WithContext visitor (even a mock if you want) and verify everything is called correctly
</blockquote></details>

Done

**Pull request merged**
